### ISSUE TITLE
Display of time elapsed?

### ISSUE THREAD

**Issue by crexes** [jmolsmobile/LandscapeVideoCamera#4]
Is there anyway to display the number of seconds the recording has been running (like in a standard camera)?

**Comment by jmolsmobile** [comment]
Hi @crexes currently there is no support for that, but you are free to build it yourself. :)

**Comment by amitclickapps** [comment]
I can't find any callback which provides the running recording time.

**Comment by amitclickapps** [comment]
can't find any callback for showing running recording time.

**Comment by JeroenMols** [comment]
@amitclickapps: small FYI, the recordingtime has been added
